<?php
   /* Some smart comment */
   return array(
       '1_chosen_as_best'=>'(1 izbran kot najboljši)', 
       '1_down_vote'=>'1 glas dol', 
       '1_up_vote'=>'1 glas gor', 
       '1_with_best_chosen'=>'(1 z najboljšim izbranim odgovorom)', 
       'activity_by_x'=>'Dejavnost od ^', //Activity by ^
       'answers'=>'Odgovori:', 
       'answers_by_x'=>'Odgovori od ^', //Answers by ^
       'bonus_points'=>'Bonus točke:', 
       'comments'=>'Komentarji:', 
       'delete_pm_popup'=>'Izbriši to zasebno sporočilo', 
       'delete_wall_post_popup'=>'Izbriši to objavo na steni', 
       'extra_privileges'=>'Dodatni privilegiji:', 
       'gave_out'=>'Predaj se:', 
       'my_account_title'=>'Moj račun', 
       'no_answers_by_x'=>'Ni odgovorov od ^', //No answers by ^
       'no_posts_by_x'=>'Ni objav od ^', //No posts by ^
       'no_questions_by_x'=>'Ni vprašanj od ^', //No questions by ^
       'permit_anon_view_ips'=>'Ogled IP-jev anonimnih objav', 
       'permit_close_q'=>'Zapri vprašanje', 
       'permit_delete_hidden'=>'Brisanje skrite objave', 
       'permit_edit_a'=>'Urejanje odgovora', 
       'permit_edit_c'=>'Urejanje komentarja', 
       'permit_edit_q'=>'Urejanje vprašanja', 
       'permit_edit_silent'=>'Potiho uredi objavo', 
       'permit_flag'=>'Označevanje objav', 
       'permit_hide_show'=>'Skrij ali prikaži objavo', 
       'permit_moderate'=>'Odobritev ali zavrnitev objave', 
       'permit_post_a'=>'Odgovarjanje na vprašanja', 
       'permit_post_c'=>'Dodajanje komentarjev', 
       'permit_post_q'=>'Postavljati vprašanja', 
       'permit_post_wall'=>'Objavljanje na steno uporabnika', 
       'permit_recat'=>'Zamenjaj kategorijo vprašanja', 
       'permit_retag'=>'Zamenjaj oznako vprašanja', 
       'permit_select_a'=>'Izbira odgovora za vprašanje', 
       'permit_view_q_page'=>'Pregled strani z vprašanji', 
       'permit_view_voters_flaggers'=>'Pregled kdo je glasoval ali označil objavo', 
       'permit_vote_a'=>'Glasovanje o odgovorih', 
       'permit_vote_down'=>'Glasovanje objav spodaj', 
       'permit_vote_q'=>'Glasovanje o vprašanjih', 
       'post_wall_blocked'=>'Ta uporabnik je onemogočil nove objave na svojem zidu', 
       'post_wall_button'=>'Dodaj objavo na steno', 
       'post_wall_empty'=>'Vnesite nekaj za objavo na tej steni', 
       'post_wall_limit'=>'Ne moreš napisati več objav na steno to uro', 
       'post_wall_must_be_approved'=>'Vaš račun mora biti odobren za objavljanje na tej steni.', 
       'post_wall_must_confirm'=>'Prosimo, ^5confirm vaš e-poštni address^6 za objavljanje na tej steni.', //Please ^5confirm your email address^6 to post on this wall.
       'post_wall_must_login'=>'Prosimo, ^1log in^2 ali ^3register^4 za objavljanje na tej steni.', //Please ^1log in^2 or ^3register^4 to post on this wall.
       'questions'=>'Vprašanja:', 
       'questions_by_x'=>'Vprašanja od ^', //Questions by ^
       'ranked_x'=>'(Uvrščen #^)', // (ranked #^)
       'received'=>'Prejeto:', 
       'recent_activity_by_x'=>'Nedavna dejavnost od ^', //Recent activity by ^
       'score'=>'Ocena:', 
       'send_private_message'=>'- ^1send zasebno message^2', // - ^1send private message^2
       'set_bonus_button'=>'Posodobitev bonusa', 
       'title'=>'Naslov:', 
       'user_x'=>'Uporabnik ^', //User ^
       'voted_on'=>'Glasoval za:', 
       'wall_for_x'=>'Stena za ^', //Wall for ^
       'wall_view_more'=>'Oglejte si več objav na steni...', 
       'x_chosen_as_best'=>'(^ izbran kot najboljši)', // (^ chosen as best)
       'x_down_votes'=>'^ negativnih glasov', //^ down votes
       'x_up_votes'=>'^ pozitivnih glasov glasov', //^ up votes
       'x_with_best_chosen'=>'(^ z najboljšim izbranim odgovorom)', // (^ with best answer chosen)
   );
