<?php
   /* Some smart comment */
   return array(
       'active_widgets_explanation'=>'Trenutno aktivni widgets:', 
       'add_category_button'=>'Dodaj Kategorija', 
       'add_field_button'=>'Dodaj polje', 
       'add_link_button'=>'Dodaj povezavo', 
       'add_link_link'=>'- ^ 1add povezava ^ 2', // - ^1add link^2
       'add_new_field'=>'Dodaj novo polje', 
       'add_new_title'=>'Dodaj nov naslov', 
       'add_page_button'=>'Dodaj stran', 
       'add_title_button'=>'Dodaj Naslov', 
       'add_widget_button'=>'Dodaj Widget', 
       'add_widget_link'=>'- ^ 1add widget ^ 2', // - ^1add widget^2
       'admin_title'=>'Uprava center', 
       'after_footer'=>'Po povezave v nogi', 
       'after_main_menu'=>'Po zavihki na vrhu', 
       'after_x'=>'Po "^"', //After "^"
       'after_x_tab'=>'Po "^" zanka', //After "^" tab
       'approve_user_popup'=>'Odobri uporabniku', 
       'approve_users_title'=>'Odobri uporabnikom', 
       'basic_editor'=>'Urejevalnik Basic', 
       'before_main_menu'=>'Pred zavihki na vrhu', 
       'blobs_directory_error'=>'Imenik ^ opredeljena kot QA_BLOBS_DIRECTORY ne more pisati na spletni strežnik.', //The directory ^ defined as QA_BLOBS_DIRECTORY is not writable by the web server.
       'blobs_move_complete'=>'Migracije naloženih slik in dokumentov končana.', 
       'blobs_move_moved'=>'Migracije ^ 1 ^ 2 naložili slik in dokumentov', //Migration ^1 of ^2 uploaded images and documents
       'blobs_stop'=>'Stop selijo', 
       'blobs_to_db'=>'Blobs do podatkovne zbirke', 
       'blobs_to_db_note'=>'- Selitev vse slike in dokumente iz diska datoteke s podatkovno zbirko', 
       'blobs_to_disk'=>'Blobs na disk', 
       'blobs_to_disk_note'=>'- Selitev vse slike in dokumentov iz baze podatkov na disk datotek', 
       'block_button'=>'blok', 
       'block_ips_note'=>'Uporabite vezaj za razpone, ali *, da se ujemajo vsako številko. Primeri: 192.168.0.4, 192.168.0.0-192.168.0.31, 192.168.0 *.', 
       'block_user_popup'=>'Blokiraj uporabnika', 
       'block_words_note'=>'Uporabite * se ujema nobenega pisma. Primeri: doh (se ujema samo točno besedno DOH), doh * (bo ujemalo doh ali dohno), naredite * h (se bo ujemalo DOH, dooh, testo).', 
       'cancel_mailing_button'=>'Prekliči poštni', 
       'categories'=>'Kategorije', 
       'categories_introduction'=>'Če želite začeti s kategorijami, kliknite "Dodaj kategorijo" gumb.', 
       'categories_not_shown'=>'Nekatera vprašanja so kategorije, ki se ne bodo prikazani.', 
       'categories_title'=>'Kategorije', 
       'category_add_sub'=>'dodaj podkategorijo', 
       'category_added'=>'Kategorija dodane', 
       'category_already_used'=>'To se ga kategoriji že uporablja', 
       'category_default_slug'=>'category- ^', //category-^
       'category_description'=>'Neobvezno opis kategorije:', 
       'category_max_depth_x'=>'Nekaj ​​možnosti je mogoče skriti, da se prepreči kategorijo gredo globlje od ^ ravni.', //Some options may be hidden to prevent a category going deeper than ^ levels.
       'category_move_parent'=>'premik k drugačni od staršev', 
       'category_name'=>'Ime kategorije:', 
       'category_name_first'=>'Ime prve kategorije:', 
       'category_no_add_subs_x'=>'Ta kategorija podkategorije, ne more imeti, ker je že ^ Ravni dol.', //This category cannot have sub-categories because it is already ^ levels down.
       'category_no_delete_subs'=>'Ta kategorija ni mogoče izbrisati, ker ima pod-kategorijo.', 
       'category_no_sub_error'=>'^ Q vprašanje / ov v tej kategoriji nima podkategorije - ^ 1set podkategorija ^ 2', //^q question/s in this category have no sub-category - ^1set sub-category^2
       'category_no_sub_to'=>'Premaknete na vprašanja v ^ brez podkategorija:', //Move questions in ^ with no sub-category to:
       'category_no_subs'=>'Noben', 
       'category_none_error'=>'^ Q vprašanje / s trenutno nimajo kategorijo - ^ kategorija 1set ^ 2', //^q question/s currently have no category - ^1set category^2
       'category_none_to'=>'Premakniti vprašanj brez kategorijo:', 
       'category_parent'=>'Nadrejena kategorija:', 
       'category_saved'=>'Kategorija shranjena', 
       'category_slug'=>'Kategorija slug - URL fragment:', 
       'category_subs'=>'Podkategoriji:', 
       'category_top_level'=>'Noben od staršev (na najvišji ravni)', 
       'characters'=>'znaki', 
       'check_language_suffix'=>'- ^ 1check jezikovne datoteke ^ 2', // - ^1check language files^2
       'click_name_edit'=>'Custom strani ali povezave:', 
       'database_cleanup'=>'Baze podatkov čistilne akcije', 
       'delete_category'=>'Izbrisati to kategorijo', 
       'delete_category_reassign'=>'Izbrisati to kategorijo in dodelite svoje vprašanja:', 
       'delete_field'=>'Izbrisati to polje', 
       'delete_hidden'=>'Brisanje skritih sporočil', 
       'delete_hidden_complete'=>'Vse skritih sporočil brez vzdrževanih so bile izbrisane', 
       'delete_hidden_note'=>'- Vse skrite vprašanja, odgovori in komentarji brez vzdrževanih družinskih članov', 
       'delete_link'=>'Izbriši to povezavo', 
       'delete_page'=>'Izbriši stran', 
       'delete_stop'=>'Stop brisanje', 
       'delete_title'=>'Izbriši ta naslov', 
       'delete_widget_position'=>'Izbriši ta widget iz tega položaja', 
       'edit_custom_page'=>'Uredite stran po meri', 
       'edit_field'=>'- ^ 1edit polje ^ 2', // - ^1edit field^2
       'edit_link'=>'- ^ 1edit povezava ^ 2', // - ^1edit link^2
       'edit_page'=>'- ^ 1edit stran ^ 2', // - ^1edit page^2
       'edit_title'=>'- ^ Naslov 1edit ^ 2', // - ^1edit title^2
       'emails_per_minute'=>'e-pošto na minuto', 
       'emails_title'=>'E-pošta', 
       'feed_link'=>'Feed', 
       'feed_link_example'=>'Primer feed', 
       'feeds_title'=>'RSS', 
       'field_link_url'=>'Povezana URL', 
       'field_multi_line'=>'Več vrstic besedila', 
       'field_name'=>'Ime polja:', 
       'field_single_line'=>'Enotni vrstica besedila', 
       'field_type'=>'Vrsta vsebine:', 
       'first'=>'Prva', 
       'flagged_title'=>'Zastavico', 
       'form_security_expired'=>'Varnostna oblika koda je potekel - poskusite znova', 
       'from_anon'=>'Iz anonimnih:', 
       'from_users'=>'Uporabnikov:', 
       'general_title'=>'Splošno', 
       'hidden_answers_deleted'=>'Črta ^ 1 od ^ 2 skritih odgovorov brez vzdrževanih ...', //Deleted ^1 of ^2 hidden answers without dependents...
       'hidden_comments_deleted'=>'Črta ^ 1 od ^ 2 skrite komentarje ...', //Deleted ^1 of ^2 hidden comments...
       'hidden_questions_deleted'=>'Črta ^ 1 od ^ 2 skritih vprašanj brez vzdrževanih ...', //Deleted ^1 of ^2 hidden questions without dependents...
       'hidden_title'=>'Skrita', 
       'hotness_factors'=>'Relativni pomen za vprašanje priljubljenosti:', 
       'ip_address_pages'=>'IP naslov strani', 
       'layout_title'=>'Postavitev', 
       'link_name'=>'Besedilo povezave:', 
       'link_new_window'=>'Odpri v novem oknu', 
       'link_url'=>'URL povezavo - absolutna ali relativna Q2A koren:', 
       'lists_title'=>'Seznami', 
       'mailing_complete'=>'Poštni je končana', 
       'mailing_explanation'=>'Uporabniki bodo lahko odjavite na njihovi strani računa.', 
       'mailing_progress'=>'Poštni izpolniti za ^ 1 od ^ 2 uporabnikov ...', //Mailing completed for ^1 of ^2 users...
       'mailing_title'=>'Mailing', 
       'mailing_unsubscribe'=>'Odjavi povezava bo dodana na dnu vsakega sporočila.', 
       'maintenance_admin_only'=>'Vaša spletna stran je v ^ 1Vzdrževanje ^ 2 in je trenutno nedostopna rednih uporabnikov.', //Your site is in ^1maintenance^2 and is currently inaccessible to regular users.
       'maximum_x'=>'(Max ^)', // (max ^)
       'moderate_title'=>'Zmerna', 
       'module_x_database_init'=>'^ 1 ^ 2 modula zahteva nekaj ^ 3database inicializacija ^ 4.', //The ^1 ^2 module requires some ^3database initialization^4.
       'most_flagged_title'=>'Označena vsebina', 
       'mysql_version'=>'MySQL verzija:', 
       'nav_links_explanation'=>'Prikaži navigacijske povezave:', 
       'nav_qa_is_home'=>'Q & A (povezave na spletno stran)', 
       'neat_urls_note'=>'(Zahteva ^ 1htaccess ^ 2 datoteke)', // (requires ^1htaccess^2 file)
       'no_approve_found'=>'Ni vsebine čaka na odobritev', 
       'no_classification'=>'Noben', 
       'no_flagged_found'=>'Ne označeni ugotovljena vsebnost', 
       'no_hidden_found'=>'Ne skrito vsebino najti', 
       'no_image_gd'=>'Nameščena različica PHP je bila prevedena brez podpore GD slike, tako da uporabniki ne morejo neposredno naložiti svoih avatarjev.', 
       'no_link'=>'Ni povezave', 
       'no_multibyte'=>'Nameščena različica PHP je bil prevedena brez podpore večbajtnega niza. Iskanje bo manj učinkovito za ne-latinico.', 
       'no_privileges'=>'Samo administratorji lahko dostopajo do te strani.', 
       'no_unapproved_found'=>'Ni uporabnikov, ki čakajo na odobritev', 
       'not_logged_in'=>'Prosimo, ^1log in ^2 kot admin za dostop do te strani.', //Please ^1log in^2 as the administrator to access this page.
       'opposite_main_menu'=>'Far konec zavihki na vrhu', 
       'options'=>'Možnosti', 
       'options_reset'=>'Ponastavi možnosti', 
       'options_saved'=>'Možnosti shranjene', 
       'page_already_used'=>'Stran že v uporabi', 
       'page_content_html'=>'Vsebino prikazati na strani - HTML dovoljeno:', 
       'page_default_slug'=>'page-^', //page-^
       'page_heading'=>'Postavka se prikaže na vrhu strani:', 
       'page_name'=>'Ime strani (uporabljajo tudi za kartice ali povezave):', 
       'page_slug'=>'Slug stran (URL fragment):', 
       'pages_explanation'=>'Kliknite na gumb "Dodaj stran", da dodate vsebino po meri za vaše Q2A mesto, ali "Add Link" za povezavo s katero koli drugo spletno stranjo.', 
       'pages_title'=>'Strani', 
       'pause_mailing_button'=>'Pause Mailing', 
       'per_ip_hour'=>'na IP / uro', 
       'per_user_hour'=>'na uporabnika / uro', 
       'permissions_title'=>'Dovoljenja', 
       'permit_to_view'=>'Vidno:', 
       'php_version'=>'PHP verzija:', 
       'pixels'=>'slikovnih pik', 
       'plugin_module'=>'(plugin modul: ^)', // (plugin module: ^)
       'plugin_pages_explanation'=>'Strani so na voljo preko vtičnikov:', 
       'plugins_title'=>'Plugins', 
       'points'=>'točke', 
       'points_defaults_shown'=>'Privzeta vrednost je prikazana spodaj, vendar se še ne uporablja:', 
       'points_required'=>'Točke se zahteva za sprejem naslova:', 
       'points_title'=>'Točke', 
       'position'=>'Položaj:', 
       'posting_title'=>'Napotitev', 
       'profile_fields'=>'Dodatna polja na uporabniških straneh ali prijavnici:', 
       'q2a_build_date'=>'Q2A ustvari datum:', 
       'q2a_db_size'=>'Velikost Q2A baze podatkov:', 
       'q2a_db_version'=>'Q2A različica zbirke podatkov:', 
       'q2a_latest_version'=>'Najnovejša Q2A različica:', 
       'q2a_version'=>'Q2A različica:', 
       'question_lists'=>'Seznam vprašanj', 
       'question_pages'=>'Strani za vprašanja', 
       'recalc_categories'=>'Preračunaj  kategorije'
       'recalc_categories_backpaths'=>'Preračunavanjem URL poti za ^1 of ^2 kategorijah...', //Recalculating URL paths for ^1 of ^2 categories...
       'recalc_categories_complete'=>'Vse kategorije so bile uspešno preračunane.', 
       'recalc_categories_note'=>'Opombe preračunanih kategorij', 
       'recalc_categories_recounting'=>'Pripoveduje vprašanja za ^1 od ^2 kategorij ...', //Recounting questions for ^1 of ^2 categories...
       'recalc_categories_updated'=>'Preračunane za ^1 od ^2 delovnih mest...', //Recalculated for ^1 of ^2 posts...
       'recalc_points'=>'Preračunaj uporabniške točke', 
       'recalc_points_complete'=>'Vse uporabniške točke so bile uspešno preračunane.', 
       'recalc_points_note'=>'- Za razvrstitev uporabnikov in točk zaslonov', 
       'recalc_points_recalced'=>'Preračunane za ^1 od ^2 uporabnikov...', //Recalculated for ^1 of ^2 users...
       'recalc_points_usercount'=>'Ocenjevanje skupnega števila uporabnikov...', 
       'recalc_posts_count'=>'Dobljeno skupno število vprašanj, odgovorov in komentarjev...', 
       'recalc_stop'=>'Ustavi preračun', 
       'recent_approve_title'=>'Nedavna čakanja za odobritev vsebine', 
       'recent_hidden_title'=>'Nedavna skrita vsebina', 
       'recount_posts'=>'Ponovno štetje objav', 
       'recount_posts_as_recounted'=>'Ponovno šteti odgovori in hotness za ^1 od ^2 objav...', //Recounted answers and hotness for ^1 of ^2 posts...
       'recount_posts_complete'=>'Vse objave so bile uspešno preštete.', 
       'recount_posts_note'=>'Opombe preštetih objav', 
       'recount_posts_stop'=>'Ustavi štetje objav', 
       'recount_posts_votes_recounted'=>'Prešteti glasovi in zastave za ^1 od ^2 delovnih mest...', //Recounted votes and flags for ^1 of ^2 posts...
       'refill_events'=>'Napolni tokove dogodkov', 
       'refill_events_complete'=>'Vsi dogodki so uspešno zaključeni', 
       'refill_events_note'=>'Za seznam posameznih uporabnikov o novostih', 
       'refill_events_refilled'=>'Ponovno napolni za ^1 od ^2 vprašanja...', //Refilled for ^1 of ^2 questions...
       'registration_fields'=>'Dodaj polja za registracijo', 
       'reindex_content'=>'Indeksiraj vsebino', 
       'reindex_content_note'=>'Predlogi in s tem povezana vprašanja', 
       'reindex_content_stop'=>'Ustavi indeksiranje', 
       'reindex_pages_reindexed'=>'Indeksiraj ^1 od ^2 strani...', //Reindexed ^1 of ^2 pages...
       'reindex_posts_complete'=>'Vse objave so bile uspešno reindeksirane.', 
       'reindex_posts_reindexed'=>'Reindeksiraj ^1 od ^2 objav...', //Reindexed ^1 of ^2 posts...
       'reindex_posts_wordcounted'=>'Prešteto ^1 od ^2 besed...', //Recounted ^1 of ^2 words...
       'requires_php_version'=>'Onemogočeno - zahteva PHP ^ ali pozneje', //Disabled - requires PHP ^ or later
       'requires_q2a_version'=>'Onemogočeno - zahteva Question2Answer ^ ali pozneje', //Disabled - requires Question2Answer ^ or later
       'reset_options_button'=>'Ponastavi na privzeto', 
       'reset_options_confirm'=>'Ali ste prepričani, da želite ponastaviti vse možnosti na tej strani na njihove privzete vrednosti?', 
       'resume_mailing_button'=>'Nadaljuj Mailing', 
       'save_options_button'=>'Možnosti shranjevanja', 
       'save_recalc_button'=>'Shrani preračun', 
       'save_view_button'=>'Shrani pogled', 
       'send_test_button'=>'Pošlji test', 
       'show_defaults_button'=>'Prikaži privzeto', 
       'show_on_register_form'=>'Prikaži na obrazec za registracijo uporabnika', 
       'slug_bad_chars'=>'Slug ne sme vsebovati teh znakov: ^', //The slug may not contain these characters: ^
       'slug_reserved'=>'Ta slug je že rezerviran za uporabo', 
       'spam_title'=>'Nezaželeno', 
       'start_mailing_button'=>'Začni pošiljanje', 
       'stats_title'=>'Statistika', 
       'stop_recalc_warning'=>'Operacija v podatkovni bazi v teku. Če zaprete to stran zdaj, bo postopek prekinjen.', 
       'tag_pages'=>'Označi strani', 
       'tags'=>'Zaznamki', 
       'tags_and_categories'=>'Zaznamki in kategorije', 
       'tags_not_shown'=>'Zaznamki, ki ne bodo prikazani.', 
       'test_sent_to_x'=>'Testno sporočilo je bilo poslano ^', //The test message was sent to ^
       'title_already_used'=>'Ta naslov je že v uporabi', 
       'top_level_categories'=>'Kategorije na najvišji ravni:', 
       'total_as'=>'Skupaj odgovorov:', 
       'total_cs'=>'Skupaj komentarjev:', 
       'total_qs'=>'Skupaj vprašanj:', 
       'unnamed_plugin'=>'Neimenovani vtičnik', 
       'upgrade_db'=>'Vaša Question2Answer baza podatkov mora biti ^1posodobljena^2 za to različico.', //Your Question2Answer database needs to be ^1upgraded^2 for this version.
       'url_format_note'=>'Možnosti z  oznako ^ delajo za konfiguracijo vašega spletnega mesta. Za najboljšo Search Engine Optimization (SEO), uporabite prvo ^ možnost na voljo.', //Options with the ^ label are working for your site's configuration. For best search engine optimization (SEO), use the first ^ option available.
       'user_pages'=>'Uporabniške strani', 
       'user_title'=>'Uporabniški naslov - HTML dovoljeno:', 
       'user_titles'=>'Uporabniški naslovoi, ki temeljijo na točkah:', 
       'users_active'=>'Aktivni uporabniki:', 
       'users_must_have'=>'Uporabniki morajo imeti', 
       'users_posted'=>'Uporabniki, ki so napoteni:', 
       'users_registered'=>'Registrirani uporabniki:', 
       'users_title'=>'Uporabniki', 
       'users_voted'=>'Uporabniki, ki so glasovali:', 
       'version_get_x'=>'dobili ^', //get ^
       'version_latest'=>'Zadnja verzija', 
       'version_latest_unknown'=>'Zadnja verzija neznana', 
       'version_requires_php'=>'^1 zahteva PHP ^2', //^1 requires PHP ^2
       'version_requires_q2a'=>'^1 zahteva Q2A ^2', //^1 requires Q2A ^2
       'viewing_title'=>'Pregled', 
       'widget_all_pages'=>'Prikaži gradnik v tem položaju na vseh razpoložljivih straneh', 
       'widget_global_options'=>'- ^1možnosti^2', // - ^1options^2
       'widget_name'=>'Ime gradnika:', 
       'widget_no_positions'=>'Ta gradnik je že dodan vsem položajem ki so na voljo.', 
       'widget_not_available'=>'Ta gradnik ni na voljo.', 
       'widget_pages_explanation'=>'Prikaži gradnik v tem položaju na naslednjih straneh:', 
       'widgets_explanation'=>'Razlaga gradnikov:', 
   );
