<?php
   /* Some smart comment */
   return array(
       '1_answer'=>'1 odgovor', 
       '1_comment'=>'1 komentar', 
       '1_day'=>'1 dan', 
       '1_disliked'=>'1 negativen glas', 
       '1_flag'=>'1 zastavica', 
       '1_hour'=>'1 ura', 
       '1_liked'=>'1 pozitiven glas', 
       '1_minute'=>'1 minuta', 
       '1_month'=>'1 mesec', 
       '1_point'=>'1 točka', 
       '1_question'=>'1 vprašanje', 
       '1_second'=>'1 drugi', 
       '1_tag'=>'1 oznaka', 
       '1_user'=>'1 uporabnik', 
       '1_view'=>'1 ogled', 
       '1_vote'=>'1 glas', 
       '1_week'=>'1 teden', 
       '1_year'=>'1 leto', 
       'add_category_x_favorites'=>'Dodaj kategorijo ^ k mojim priljubljenim', //Add category ^ to my favorites
       'add_favorites'=>'Dodaj k mojim priljubljenim', 
       'add_tag_x_favorites'=>'Dodaj oznako ^ k mojim priljubljenim', //Add tag ^ to my favorites
       'all_categories'=>'Vse kategorije', 
       'anonymous'=>'Anonimen', 
       'answer_edited'=>'odgovor je urejen', 
       'answer_reshown'=>'Odgovor je ponovno prikazan', 
       'answer_selected'=>'Odgovor je izbran', 
       'answered'=>'odgovorjeno', 
       'answered_qs_in_x'=>'Največkrat odgovorjena vprašanja v ^', //Most answered questions in ^
       'answered_qs_title'=>'Največkrat odgovorjeno vprašanje', 
       'asked'=>'vprašano', 
       'asked_related_q'=>'povezano z vprašanim', 
       'by_x'=>'od ^', //by ^
       'cancel_button'=>'Prekliči', 
       'closed'=>'zaprto', 
       'comment_edited'=>'komentar uredil', 
       'comment_moved'=>'komentar premaknjen', 
       'comment_reshown'=>'komentar ponovno prikaži', 
       'commented'=>'komentirano', 
       'date_day_min_digits'=>'1',
       'date_format_other_years'=>' ^month ^day, ^year', //^month ^day, ^year
       'date_format_this_year'=>' ^month ^day', //^month ^day
       'date_month_1'=>'Januar', 
       'date_month_10'=>'Oktober', 
       'date_month_11'=>'November', 
       'date_month_12'=>'December', 
       'date_month_2'=>'Februar', 
       'date_month_3'=>'Marec', 
       'date_month_4'=>'April', 
       'date_month_5'=>'Maj', 
       'date_month_6'=>'Junij', 
       'date_month_7'=>'Julij', 
       'date_month_8'=>'Avgust', 
       'date_month_9'=>'September', 
       'date_year_digits'=>'4',
       'edited'=>'urejeno', 
       'email_error'=>'Prišlo je do napake pri pošiljanju e-pošte.', 
       'field_required'=>'Polje ne sme biti prazno!', 
       'file_upload_limit_exceeded'=>'Velikost datoteke presega omejitev strežnika', 
       'general_error'=>'Prišlo je do napake na strežniku - poskusite znova.', 
       'hidden'=>'skrito', 
       'highest_users'=>'Uporabniki z največ točkami ', 
       'hot_qs_in_x'=>'Aktualna vprašanja v ^', //Hot questions in ^
       'hot_qs_title'=>'Aktualna vprašanja', 
       'image_not_read'=>'Slike ni bilo mogoče prebrati. Prosimo, prenesite eno izmed: ^', //The image could not be read. Please upload one of: ^
       'image_too_big_x_pc'=>'Ta slika je prevelika. Prosimo, izberite sliko, ki je manjša od ^% in poskusite znova.', //This image is too big. Please scale to ^% then try again.
       'in_category_x'=>'v ^', //in ^
       'ip_address_x'=>'IP naslov ^', //IP address ^
       'logged_in_x'=>'Pozdravljeni! ^', //Hello ^
       'max_length_x'=>'Največja dolžina je ^ znakov', //Maximum length is ^ characters
       'max_upload_size_x'=>'Največja velikost, ki jo lahko naložite je ^', //Maximum upload size is ^
       'me'=>'jaz',
       'meta_order'=>'^what^when^where^who', //^what^when^where^who
       'min_length_x'=>'Prosimo, zagotovite več informacij - vsaj ^ znakov', //Please provide more information - at least ^ characters
       'moved'=>'premaknjeno', 
       'nav_activity'=>'Vse dejavnosti', 
       'nav_admin'=>'Administrator', 
       'nav_ask'=>'Zastavi vprašanje', 
       'nav_categories'=>'Kategorije', 
       'nav_feedback'=>'Pošlji povratno informacijo', 
       'nav_home'=>'Domov', 
       'nav_hot'=>'Aktualno!', 
       'nav_login'=>'Prijava', 
       'nav_logout'=>'Odjava', 
       'nav_most_answers'=>'Največ odgovorov', 
       'nav_most_recent'=>'Nedavna', 
       'nav_most_views'=>'Največ ogledov', 
       'nav_most_votes'=>'Največ glasov', 
       'nav_no_answer'=>'Brez odgovora', 
       'nav_no_selected_answer'=>'Ni izbranega odgovora', 
       'nav_no_upvoted_answer'=>'Ni pozitivno ocenjenega odgovora', 
       'nav_qa'=>'Vprašanja in odgovori', 
       'nav_qs'=>'Vprašanja', 
       'nav_register'=>'Registriraj se', 
       'nav_tags'=>'Oznake', 
       'nav_unanswered'=>'Neodgovorjeno', 
       'nav_updates'=>'Moje posodobitve', 
       'nav_users'=>'Uporabniki', 
       'no_active_users'=>'Ni najdenih aktivnih uporabnikov', 
       'no_answers_found'=>'Ni najdenih odgovorov', 
       'no_answers_in_x'=>'Ni odgovorov v ^', //No answers in ^
       'no_categories_found'=>'Ni najdenih kategoriji', 
       'no_category'=>'Ni kategorije', 
       'no_comments_found'=>'Ni najdenih komentarjev', 
       'no_comments_in_x'=>'Ni komentarjev v ^', //No comments in ^
       'no_questions_found'=>'Ni najdenih vprašanj', 
       'no_questions_in_x'=>'Ni vprašanj v ^', //No questions in ^
       'no_related_qs_title'=>'Ni sorodnih vprašanj', 
       'no_results_for_x'=>'Ni zadetkov za ^', //No results found for ^
       'no_tags_found'=>'Ni najdenih oznak', 
       'no_una_questions_found'=>'Ni najdenih neodgovorjenih vprašanj', 
       'no_una_questions_in_x'=>'Ni neodgovorjenih vprašanj v ^', //No unanswered questions in ^
       'no_unselected_qs_found'=>'Ni najdenih vprašanj brez izbranega odgovora', 
       'no_unupvoteda_qs_found'=>'Ni najdenih vprašanj brez pozitivno ocenjenega odgovora', 
       'page_label'=>'Stran:', 
       'page_next'=>'Naslednji', 
       'page_not_found'=>'Strani ni mogoče najti', 
       'page_prev'=>'Prejšnji', 
       'popular_tags'=>'Priljubljene oznake', 
       'questions_tagged_x'=>'Nedavno označena vprašanja ^', //Recent questions tagged ^
       'recategorized'=>'prerazporejeno', 
       'recent_activity_in_x'=>'Nedavna dejavnost v ^', //Recent activity in ^
       'recent_activity_title'=>'Nedavna dejavnost', 
       'recent_as_in_x'=>'Pred kratkim odgovorjena vprašanja v ^', //Recently answered questions in ^
       'recent_as_title'=>'Pred kratkim odgovorjena vprašanja', 
       'recent_cs_in_x'=>'Pred kratkim komentirana vprašanja v ^', //Recently commented questions in ^
       'recent_cs_title'=>'Pred kratkim komentirana vprašanja', 
       'recent_qs_as_in_x'=>'Nedavna vprašanja in odgovori v ^', //Recent questions and answers in ^
       'recent_qs_as_title'=>'Nedavna vprašanja in odgovori', 
       'recent_qs_in_x'=>'Nedavna vprašanja v ^', //Recent questions in ^
       'recent_qs_title'=>'Nedavna vprašanja', 
       'related_qs_title'=>'Povezana vprašanja', 
       'remove_favorites'=>'Odstrani iz priljubljenih', 
       'remove_x_favorites'=>'Odstrani ^ iz priljubljenih', //Remove ^ from my favorites
       'reopened'=>'ponovno odprt', 
       'reshown'=>'ponovno prikazan', 
       'results_for_x'=>'Rezultati iskanja za ^', //Search results for ^
       'retagged'=>'ponovno označen', 
       'save_button'=>'Shrani spremembe', 
       'search_button'=>'Iskanje', 
       'search_explanation'=>'V iskalno polje vnesite besedilo in poskusite znova.', 
       'search_title'=>'Rezultati iskanja', 
       'selected'=>'izbrano', 
       'send_button'=>'Pošlji', 
       'since_x'=>'od ^', //since ^
       'suggest_ask'=>'Pomagaj nam začeti z ^1asking a question^2.', //Help get things started by ^1asking a question^2.
       'suggest_category_qs'=>'Če si želite ogledati več, kliknite za vse ^1questions in this category^2.', //To see more, click for all the ^1questions in this category^2.
       'suggest_qs'=>'Če si želite ogledati več kliknite za ^1full list of questions^2.', //To see more, click for the ^1full list of questions^2.
       'suggest_qs_tags'=>'Če si želite ogledati več kliknite za ^1full list of questions^2 ali ^3popular tags^4.', //To see more, click for the ^1full list of questions^2 or ^3popular tags^4.
       'to_x'=>'na ^', //to ^
       'unanswered_qs_in_x'=>'Vprašanja brez odgovorov v ^', //Questions without answers in ^
       'unanswered_qs_title'=>'Nedavna vprašanja brez odgovorov', 
       'unselected_qs_in_x'=>'Vprašanja brez izbranega odgovora v ^', //Questions without a selected answer in ^
       'unselected_qs_title'=>'Nedavna vprašanja brez izbranega odgovora', 
       'unupvoteda_qs_in_x'=>'Vprašanja brez pozitivno ocenjenega odgovora v ^', //Questions without an upvoted answer in ^
       'unupvoteda_qs_title'=>'Nedavna vprašanja brez pozitivno ocenjenega odgovora', 
       'upload_limit'=>'Strežnik je preobremenjen - poskusite znova čez eno uro', 
       'view_q_must_be_approved'=>'Vaš račun mora biti potrjen za ogled strani z vprašanji.', 
       'view_q_must_confirm'=>'Prosimo, ^5confirm your email address^6, če želite videti strani z vprašanji.', //Please ^5confirm your email address^6 to view question pages.
       'view_q_must_login'=>'Prosimo, ^1log in^2 ali ^ 3register^4, če želite videti strani z vprašanji.', //Please ^1log in^2 or ^3register^4 to view question pages.
       'viewed_qs_in_x'=>'Največkrat ogledana vprašanja v ^', //Most viewed questions in ^
       'viewed_qs_title'=>'Največkrat ogledana vprašanja', 
       'vote_disabled_approve'=>'Vaš račun mora biti potrjen, preden lahko glasujete', 
       'vote_disabled_down'=>'Negativno glasovanje je na voljo samo za nekatere uporabnike', 
       'vote_disabled_down_approve'=>'Za negativen glas mora biti vaš račun potrjen', 
       'vote_disabled_hidden_a'=>'Skritemu odgovoru ne morete dati glasu', 
       'vote_disabled_hidden_q'=>'Skritemu vprašanju ne morete dati glasu', 
       'vote_disabled_level'=>'Glasovanje je na voljo samo za nekaterim uporabnikom', 
       'vote_disabled_my_a'=>'Ne morete glasovati za svoj odgovor', 
       'vote_disabled_my_q'=>'Ne morete glasovati za svoje vprašanje', 
       'vote_disabled_q_page_only'=>'Prosimo, oglejte si to vprašanje, če želite glasovati', 
       'vote_down_must_confirm'=>'Prosimo, ^5confirm your email address^6, če želite glasovati negativno.', //Please ^5confirm your email address^6 to vote down.
       'vote_down_popup'=>'Kliknite, če želite glasovati negativno', 
       'vote_limit'=>'Prejetih je bilo preveč glasov - poskusite znova čez eno uro', 
       'vote_must_confirm'=>'Prosimo, ^5confirm your email address^6 če želite glasovati.', //Please ^5confirm your email address^6 to vote.
       'vote_must_login'=>'Prosimo, ^1log in^2 ali ^3register^4, če želite glasovati.', //Please ^1log in^2 or ^3register^4 to vote.
       'vote_not_allowed'=>'Glasovanje ni dovoljeno', 
       'vote_up_popup'=>'Kliknite, če želite oddati pozitiven glas', 
       'voted_down_popup'=>'Oddali ste negativen glas - kliknite, če želite umakniti svoj glas', 
       'voted_qs_in_x'=>'Vprašanja z najboljšo oceno v ^', //Highest voted questions in ^
       'voted_qs_title'=>'Vprašanja z najboljšo oceno', 
       'voted_up_popup'=>'Oddali ste pozitiven glas - kliknite, če želite umakniti svoj glas', 
       'written'=>'', 
       'x_ago'=>'^ Pred', //^ ago
       'x_answers'=>'^ odgovori', //^ answers
       'x_comments'=>'^ komentarji', //^ comments
       'x_days'=>'^ dni', //^ days
       'x_disliked'=>'^ Negativen glas', //^ dislike
       'x_flags'=>'^ zastavice', //^ flags
       'x_hours'=>'^ ur', //^ hours
       'x_liked'=>'^ Pozitiven glas', //^ like
       'x_minutes'=>'^ minut', //^ minutes
       'x_months'=>'^ mesecev', //^ months
       'x_points'=>'^ točk', //^ points
       'x_questions'=>'^ vprašanja', //^ questions
       'x_seconds'=>'^ sekund', //^ seconds
       'x_tags'=>'^ oznake', //^ tags
       'x_users'=>'^ uporabniki', //^ users
       'x_views'=>'^ ogledov', //^ views
       'x_votes'=>'^ glasov', //^ votes
       'x_weeks'=>'^ tednov', //^ weeks
       'x_years'=>'^ let', //^ years
   );
