<?php
   /* Some smart comment */
   return array(
       '1_chosen_as_best'=>'(1 izbrana kot najboljša)', 
       '1_down_vote'=>'1 dol glas', 
       '1_up_vote'=>'1 do glasovanja', 
       '1_with_best_chosen'=>'(1 z izbrala najboljši odgovor)', 
       'activity_by_x'=>'Dejavnost, ki jo ^', //Activity by ^
       'answers'=>'Odgovori:', 
       'answers_by_x'=>'Odgovori, ki jih ^', //Answers by ^
       'bonus_points'=>'Bonus točke:', 
       'comments'=>'Komentarji:', 
       'delete_pm_popup'=>'Izbriši to zasebno sporočilo', 
       'delete_wall_post_popup'=>'Izbriši to sten objavo', 
       'extra_privileges'=>'Extra privilegije:', 
       'gave_out'=>'Dal ven:', 
       'my_account_title'=>'Moj račun', 
       'no_answers_by_x'=>'Ni odgovorov, ki jih ^', //No answers by ^
       'no_posts_by_x'=>'Ni objav z ^', //No posts by ^
       'no_questions_by_x'=>'Brez vprašanj, ki jih ^', //No questions by ^
       'permit_anon_view_ips'=>'Ogled IP anonimnih objav', 
       'permit_close_q'=>'Zapiranje vprašanje', 
       'permit_delete_hidden'=>'Brisanje skrite objave', 
       'permit_edit_a'=>'Urejanje odgovora', 
       'permit_edit_c'=>'Urejanje nobenega komentarja', 
       'permit_edit_q'=>'Urejanje vsako vprašanje', 
       'permit_edit_silent'=>'Urejanje objav tiho', 
       'permit_flag'=>'Vpisovanja objav', 
       'permit_hide_show'=>'Skrivanje ali kar koli delovno mesto', 
       'permit_moderate'=>'Odobritev ali zavrnitev objave', 
       'permit_post_a'=>'Odgovarjanje na vprašanja', 
       'permit_post_c'=>'Dodajanje komentarjev', 
       'permit_post_q'=>'Postavljati vprašanja', 
       'permit_post_wall'=>'Napotitev na uporabniških stenah', 
       'permit_recat'=>'Recategorizing vsako vprašanje', 
       'permit_retag'=>'Retagging vsako vprašanje', 
       'permit_select_a'=>'Izbira odgovor za vsako vprašanje', 
       'permit_view_q_page'=>'Pregled vprašanje straneh', 
       'permit_view_voters_flaggers'=>'Pregled, ki so glasovali, ali zastavico objave', 
       'permit_vote_a'=>'Glasovanje o odgovorih', 
       'permit_vote_down'=>'Glasovalne objav navzdol', 
       'permit_vote_q'=>'Glasovanje o vprašanjih', 
       'post_wall_blocked'=>'Ta uporabnik je zavrnili nove objave na svojem zidu', 
       'post_wall_button'=>'Dodaj sten objavo', 
       'post_wall_empty'=>'Vnesite nekaj za objavo na tej steni', 
       'post_wall_limit'=>'Ne moreš napisati več Komentarjev ta ura', 
       'post_wall_must_be_approved'=>'Vaš račun morajo biti odobreni za objavo na tej steni.', 
       'post_wall_must_confirm'=>'Prosimo, ^ 5confirm vaš e-poštni naslov ^ 6 za objavo na tej steni.', //Please ^5confirm your email address^6 to post on this wall.
       'post_wall_must_login'=>'Prosimo, ^ 1log v ^ 2 ali ^ 3register ^ 4 za objavo na tej steni.', //Please ^1log in^2 or ^3register^4 to post on this wall.
       'questions'=>'Vprašanja:', 
       'questions_by_x'=>'Vprašanja, ki jih ^', //Questions by ^
       'ranked_x'=>'(Uvrščen # ^)', // (ranked #^)
       'received'=>'Prejeto:', 
       'recent_activity_by_x'=>'Nedavna dejavnost, ki jo ^', //Recent activity by ^
       'score'=>'Ocena:', 
       'send_private_message'=>'- ^ 1send zasebno sporočilo ^ 2', // - ^1send private message^2
       'set_bonus_button'=>'Bonus Update', 
       'title'=>'Naslov:', 
       'user_x'=>'Uporabnik ^', //User ^
       'voted_on'=>'Glasoval o:', 
       'wall_for_x'=>'Wall za ^', //Wall for ^
       'wall_view_more'=>'Oglejte si več stenskih prispevke ...', 
       'x_chosen_as_best'=>'(^ Izbrana kot najboljša)', // (^ chosen as best)
       'x_down_votes'=>'^ navzdol glasov', //^ down votes
       'x_up_votes'=>'^ up glasov', //^ up votes
       'x_with_best_chosen'=>'(^ Z izbrala najboljši odgovor)', // (^ with best answer chosen)
   );